[font]
size = 10.0

[window]
opacity = 1 #.9

[window.padding]
x = 15
y = 10

[colors.primary]
background = '#0d0d0d'
foreground = '#a9b1d6'

[colors.normal]
black   = '#32344a'
red     = '#7a4848'
green   = '#487a58'
yellow  = '#797a48'
blue    = '#38457c'
magenta = '#54487a'
cyan    = '#487a77'
white   = '#787c99'

[colors.bright]
black   = '#444b6a'
red     = '#a15e5e'
green   = '#5ea173'
yellow  = '#909155'
blue    = '#4f61b0'
magenta = '#6e56af'
cyan    = '#5ea19c'
white   = '#acb0d0'
